# Configuration for pyquizhub
storage:
  type: "file"  # Options: file, sql
  file:
    base_dir: ".pyquizhub"  # Default storage location
  sql:
    connection_string: "sqlite:///pyquizhub.db"  # SQLAlchemy connection string

api:
  base_url: "http://127.0.0.1:8000"
  host: "0.0.0.0"  # Host for uvicorn
  port: 8000       # Port for uvicorn

security:
  use_tokens: true
  admin_token_env: "PYQUIZHUB_ADMIN_TOKEN"
  creator_token_env: "PYQUIZHUB_CREATOR_TOKEN"
  user_token_env: "PYQUIZHUB_USER_TOKEN"

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: standard
      filename: .pyquizhub/logs/pyquizhub.log
      maxBytes: 1048576
      backupCount: 5
  root:
    level: DEBUG
    handlers: [console, file]
  loggers:
    pyquizhub:
      level: DEBUG
      handlers: [console, file]
      propagate: false