# Configuration for pyquizhub
storage:
  type: "file"  # Options: file, sql
  file:
    base_dir: ".pyquizhub"  # Default storage location
  sql:
    connection_string: "sqlite:///pyquizhub.db"  # SQLAlchemy connection string

api:
  base_url: "http://127.0.0.1:8000"
  host: "0.0.0.0"  # Host for uvicorn
  port: 8000       # Port for uvicorn

security:
  use_tokens: true
  admin_token_env: "PYQUIZHUB_ADMIN_TOKEN"
  creator_token_env: "PYQUIZHUB_CREATOR_TOKEN"
  user_token_env: "PYQUIZHUB_USER_TOKEN"

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file:
    enabled: true
    path: ".pyquizhub/logs/pyquizhub.log"
    max_size: 1048576  # 1MB
    backup_count: 5
    level: "DEBUG"
  console:
    enabled: true
    level: "INFO"