# Configuration for pyquizhub
storage:
  type: "file"  # Options: file, sql
  file:
    base_dir: ".pyquizhub"  # Default storage location
  sql:
    connection_string: "sqlite:///pyquizhub.db"  # SQLAlchemy connection string

api:
  base_url: "http://127.0.0.1:8000"

security:
  use_tokens: true
  admin_token_env: "PYQUIZHUB_ADMIN_TOKEN"
  creator_token_env: "PYQUIZHUB_CREATOR_TOKEN"
  user_token_env: "PYQUIZHUB_USER_TOKEN"